"""review Migration

Revision ID: 2038f6e78626
Revises: 8bb91c249961
Create Date: 2018-07-02 23:42:48.600282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2038f6e78626'
down_revision = '8bb91c249961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewadvertisement', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviewadvertisement', 'comment')
    op.add_column('reviewgeneral', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviewgeneral', 'comment')
    op.add_column('reviewmusic', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviewmusic', 'comment')
    op.add_column('reviewsale', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviewsale', 'comment')
    op.add_column('reviewseduction', sa.Column('review', sa.String(length=255), nullable=True))
    op.drop_column('reviewseduction', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewseduction', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviewseduction', 'review')
    op.add_column('reviewsale', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviewsale', 'review')
    op.add_column('reviewmusic', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviewmusic', 'review')
    op.add_column('reviewgeneral', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviewgeneral', 'review')
    op.add_column('reviewadvertisement', sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviewadvertisement', 'review')
    # ### end Alembic commands ###
